language: node_js
dist: xenial
node_js:
  - "5.9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install --quiet -g karma

script: xvfb-run grunt
sudo: false
